blog/urls.py
from django.urls import path, re_path
from . import views

app_name = "blog"
urlpatterns = [
    # https:localhost:8000/blog/1
    path("", views.blog_list, name="blog_list"),
    path("<int:blog_id>", views.blog_detail, name="blog_detail"),
    path("type/<int:id>", views.blogs_with_type, name="blog_with_type"),
    path("date", views.blogs_with_date, name="blog_with_date"),
    path("about", views.about_me, name="about_me")
]

comment/urls.py
from django.urls import path
from . import views

app_name = "comment"
urlpatterns = [
    path("update_comment", views.update_comment, name="update_comment")
]

likes/urls.py
from django.urls import path
from . import views

app_name = "likes"
urlpatterns = [
    path("like_change", views.like_change, name="like_change")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from blog import views as blog_views
urlpatterns = [
    path("", blog_views.blog_list, name="home"),
    path('admin/', admin.site.urls),
    path("ckeditor", include("ckeditor_uploader.urls")),
    path("blog/", include("blog.urls")),
    path("comment/", include("comment.urls")),
    path("likes/", include("likes.urls")),
    path("user/", include("user.urls")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from ckeditor_uploader.fields import RichTextUploadingField
from read_statistics.models import GetReadNum, ReadDetail


class BlogType(models.Model):
    type_name = models.CharField(max_length=15)

    def __str__(self):
        return "{}".format(self.type_name)


class Blog(models.Model, GetReadNum):
    title = models.CharField(max_length=50)
    blog_type = models.ForeignKey(BlogType, on_delete=models.CASCADE)
    content = RichTextUploadingField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    read_details = GenericRelation(ReadDetail)
    create_time = models.DateTimeField(auto_now_add=True)
    last_updated_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "Blog: {}".format(self.title)

    class Meta:
        ordering = ["-create_time"]

blog/views.py
import markdown, re
from django.shortcuts import render, get_object_or_404
from django.utils.safestring import mark_safe
from django.core.paginator import Paginator
from .models import Blog, BlogType
from django.contrib.contenttypes.models import ContentType
from read_statistics.utils import ReadStatistics, popular_articles
from comment.models import Comment
from comment.forms import CommentForm
from user.forms import LoginForm

per_page_blogs = 5


def common_data(request, blogs_all_list):
    paginator = Paginator(blogs_all_list, per_page_blogs)
    page_num = request.GET.get("page", 1)
    page_of_blogs = paginator.get_page(page_num)
    current_page_num = page_of_blogs.number  # 获取当前页码
    page_range = list(
        range(max(current_page_num - 2, 1), min(current_page_num + 3, paginator.num_pages + 1)))  # 防止出现-1，0这样情况
    # 加上省略页码标记
    if page_range[0] - 1 >= 2:
        page_range.insert(0, "...")
    if paginator.num_pages - page_range[-1] >= 2:
        page_range.append("...")
    # 加上首页和尾页
    if page_range[0] != 1:
        page_range.insert(0, 1)
    if page_range[-1] != paginator.num_pages:
        page_range.append(paginator.num_pages)
    context = {
        "blogs": Blog.objects.all(),
        "page_of_blogs": page_of_blogs,
        "page_range": page_range,
        "blog_count": Blog.objects.all().count(),
        "blog_types": BlogType.objects.all(),
        "blog_dates": Blog.objects.dates("create_time", "month", order="DESC")
    }
    return context


def blog_list(request):
    blog_content_type = ContentType.objects.get_for_model(Blog)
    blogs_all_list = Blog.objects.all()
    context = common_data(request, blogs_all_list)
    context["popular_articles"] = popular_articles(blog_content_type)
    return render(request, "blog/blog_list.html", context=context)


def blog_detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    # 浏览器再次刷新时不会更新阅读数
    read_cookie_key = ReadStatistics(request, blog)
    blog_content_type = ContentType.objects.get_for_model(blog)
    comments = Comment.objects.filter(content_type=blog_content_type, object_id=blog.pk,
                                      parent=None)
    # 支持markdown语法
    config = {
        'codehilite': {
            'use_pygments': False,
            'css_class': 'prettyprint linenums',
        }
    }
    # strip_html = re.sub('<[^<]+?>', '', blog.content)
    blog.body = markdown.markdown(blog.content,
                                  extensions=['codehilite'], extension_configs=config)
    data = {
        "content_type": blog_content_type.model,
        "object_id": blog_id,
        "reply_comment_id": 0,
    }
    context = {
        "blog": blog,
        "previous_blog": Blog.objects.filter(create_time__gt=blog.create_time).last(),
        "next_blog": Blog.objects.filter(create_time__lt=blog.create_time).first(),
        "comments": comments.order_by("-comment_time"),
        "comments_count": Comment.objects.filter(content_type=blog_content_type, object_id=blog.pk).count(),
        "comment_form": CommentForm(initial=data),
        "login_form": LoginForm()
    }
    response = render(request, "blog/blog_detail.html", context)
    response.set_cookie(read_cookie_key, "true")  # 设置cookie
    return response


def blogs_with_type(request, id):
    blog_content_type = ContentType.objects.get_for_model(Blog)
    blog_type = get_object_or_404(BlogType, pk=id)
    blogs_all_list = Blog.objects.filter(blog_type=blog_type)
    context = common_data(request, blogs_all_list)
    context["blog_type"] = blog_type
    context["popular_articles"] = popular_articles(blog_content_type)
    return render(request, "blog/blogs_with_type.html", context=context)


def blogs_with_date(request):
    blogs_all_list = Blog.objects.all()
    context = common_data(request, blogs_all_list)
    return render(request, "blog/blogs_with_date.html", context=context)


def about_me(request):
    return render(request, "blog/about_me.html")

blog/templates/blog/about_me.html
{% extends "base.html" %}
{% load static %}
{% load blog_tags %}
{% block title %}
    关于
{% endblock %}
{% block nav_blog_active %}
    active
{% endblock %}
{% block header_extends %}
    <link rel="stylesheet" href="{% static "blog/blog_archive.css" %}">
{% endblock %}
{% block content %}
    <div class="archive-container">
        <div class="container archive">
            <h3>关于我</h3>
            <p>自学Python一年，Python爱好者，喜欢写代码，目前正在学习Django，喜欢研究技术问题</p>
            <h3>关于博客</h3>
            <p>此博客基于Python3.6+Django2.0开发，目的是希望整理学习上的笔记，记录下学习中遇到的难题</p>
            <h3>联系我</h3>
            <p>
            <ul>
                <li>微信：sy151323</li>
                <li>邮箱：1754935816@qq.com</li>
            </ul>
            <p>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "base.html" %}
{% load static %}
{% load likes_tags %}
{% load blog_tags %}
{% block title %}
    {{ blog.title }}
{% endblock %}
{% block header_extends %}
    <link rel="stylesheet" href="{% static "blog/blog_detail.css" %}">
    <link rel="stylesheet" href="{% static "blog/prettify.css" %}">
    <link rel="stylesheet" href="{% static "blog/desert.css" %}">
    <script type="text/javascript" src="{% static "blog/prettify.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}
{% block content %}
    <div class="container content">
        <div class="row">
            {#            <div class="col-xs-10 col-xs-offset-1">#}
            <h3>{{ blog.title }}</h3>
            <ul class="blog-info-description ">
                <li><span class="glyphicon glyphicon-tag"></span>
                    <a href="{% url "blog:blog_with_type" blog.blog_type.id %}">{{ blog.blog_type }}</a>
                </li>
                <li><span class="glyphicon glyphicon-calendar"></span>{{ blog.create_time|date:"Y-m-d H:i:s" }}</li>
                <li><span class="glyphicon glyphicon-eye-open"></span>{{ blog.get_read_num }}</li>
                <li><span class="glyphicon glyphicon-comment"></span>{{ comments_count }}</li>
                <div class="like" onclick="likeChange(this, '{% get_content_type blog %}', {{ blog.pk }})">
                    <span class="glyphicon glyphicon-thumbs-up {% get_like_status blog %} "></span>
                    <span class="liked-num">{{ blog|likes_count }}</span>
                </div>
            </ul>
            <div class="blog-content">{{ blog.body|safe }}</div>

            <div class="blog-more">
                <p>
                    {% if previous_blog %}
                        <a href="{% url "blog:blog_detail" previous_blog.pk %}">上一篇</a>
                    {% else %}
                        <a href=#> 没有了</a>
                    {% endif %}
                </p>
                <p class="nav pull-right">
                    {% if next_blog %}
                        <a href="{% url "blog:blog_detail" next_blog.pk %}">下一篇</a>
                    {% else %}
                        <a href=#> 没有了</a>
                    {% endif %}
                </p>
            </div>
            {#            </div>#}
        </div>
        <div class="row">
            <div class="comment-area">
                <h3 class="comment-area-title">提交评论</h3>
                {% if user.is_authenticated %}
                    <form id="comment_form" action="{% url "comment:update_comment" %}" method="POST"
                          style="overflow: hidden">
                        <label>{{ user.username }}, 欢迎评论</label>
                        <div id="reply_content_container" style="display: none">
                            <p id="reply_title">回复：</p>
                            <div id="reply_content"></div>
                        </div>
                        {% csrf_token %}
                        {% for field in comment_form %}
                            {{ field }}
                        {% endfor %}
                        <span id="comment_error" class="text-danger pull-left"></span>
                        <input type="submit" value="评论" class="btn btn-primary pull-right">
                    </form>
                {% else %}
                    你尚未登录，登录之后方可评论
                    <a class="btn btn-primary" href="{% url "login" %}?from={{ request.get_full_path }}">登录</a>
                    <span> or </span>
                    <a class="btn btn-danger" href="{% url "register" %}?from={{ request.get_full_path }}">注册</a>
                {% endif %}
            </div>
            <div class="comment-area">
                <h3 class="comment-area-title">评论列表</h3>
                <div id="comment_list">
                    {% for comment in comments %}
                        <div id="root_{{ comment.pk }}" class="comment">
                            <span>{{ comment.user.username }}</span>
                            <span>({{ comment.comment_time|date:"Y-m-d H:i:s" }})：</span>
                            <div id="comment_{{ comment.pk }}">
                                {{ comment.content|safe }}
                            </div>
                            <a href="javascript:reply({{ comment.pk }})">回复</a>

                            {% for reply in comment.root_comment.all %}
                                <div class="reply">
                                    <span>{{ reply.user.username }}</span>
                                    <span>({{ reply.comment_time|date:"Y-m-d H:i:s" }})</span>
                                    <span>回复</span>
                                    <span>{{ reply.reply_to.username }}</span>
                                    <div id="comment_{{ reply.pk }}">
                                        {{ reply.content|safe }}
                                    </div>
                                    <a href="javascript:reply({{ reply.pk }})">回复</a>
                                </div>
                            {% endfor %}
                        </div>
                    {% empty %}
                        <span id="no_comment">暂无评论</span>
                    {% endfor %}
                </div>
            </div>

        </div>
        <div class="modal fade" id="login_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <form id="login_modal" method="post">
                        {% csrf_token %}
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">登录</h4>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <input type="text" class="form-control" name="username" placeholder="用户名">
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" name="password" placeholder="密码">
                            </div>
                            <span class="pull-right text-danger">{{ login_form.non_field_errors }}</span>
                            <p class="text-danger">{{ field.errors.as_text }}</p>
                            <div class="form-group">
                                <button type="submit" class="btn btn-warning btn-block" id="submit-btn">立即登录</button>
                            </div>
                            <span id="login_modal_tip" class="text-danger"></span>
                            <div class="form-group">
                                <a href={% url "register" %} class="signup_link">没有账号？立即注册</a>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block nav_blog_active %}
    active
{% endblock %}

{% block script_extedns %}
    <script type="text/javascript">
        $(document).ready(function () {
           $("pre").addClass("prettyprint");
           PR.prettyPrint();
        });
        function reply(reply_comment_id) {
            $("#reply_comment_id").val(reply_comment_id);
            var html = $("#comment_" + reply_comment_id).html();
            $("#reply_content").html(html);
            $("#reply_content_container").show();
            $("html").animate({scrollTop: $("#comment_form").offset().top - 60}, 300, function () {
                CKEDITOR.instances["id_text"].focus()
            })
        }
        function numFormat(num) {
            return ('00' + num).substr(-2);
        }
        function timeFormat(timestamp) {
            var datetime = new Date(timestamp * 1000);
            var year = datetime.getFullYear();
            var month = numFormat(datetime.getMonth() + 1);
            var day = numFormat(datetime.getDate());
            var hour = numFormat(datetime.getHours());
            var minute = numFormat(datetime.getMinutes());
            var second = numFormat(datetime.getSeconds());
            return year + '-' + month + '-' + day + ' ' + hour + ':' + minute + ':' + second;
        }
        $("#comment_form").submit(function () {
            // 判断是否为空
            $("#comment_error").text('');
            if (CKEDITOR.instances["id_text"].document.getBody().getText().trim() == '') {
                $("#comment_error").text('评论内容不能为空');
                return false;
            }
            // 更新数据到textarea
            CKEDITOR.instances["id_text"].updateElement();
            // 异步提交
            $.ajax({
                url: "{% url "comment:update_comment" %}",
                type: "POST",
                data: $(this).serialize(),
                cache: false,
                success: function (data) {
                    console.log(data);
                    if (data['status'] == "SUCCESS") {
                        if ($('#reply_comment_id').val() == '0') {
                            // 插入评论
                            var comment_html = '<div id="root_' + data['pk'] + '" class="comment"><span>' + data['username'] + '</span><span> (' + timeFormat(['comment_time']) + ')：</span><div id="comment_' + data['pk'] + '">' + data['text'] + '</div><a href="javascript:reply(' + data['pk'] + ');">回复</a></div>';
                            $("#comment_list").prepend(comment_html);
                        } else {
                            // 插入回复
                            var reply_html = '<div class="reply"><span>' + data['username'] + '</span><span> (' + timeFormat(['comment_time']) + ')</span><span> 回复 </span><span>' + data['reply_to'] + '：</span><div id="comment_' + data['pk'] + '">' + data['text'] + '</div><a href="javascript:reply(' + data['pk'] + ');">回复</a></div>';
                            $("#root_" + data['root_pk']).append(reply_html);
                        }

                        // 清空编辑框的内容
                        CKEDITOR.instances['id_text'].setData('');
                        $('#reply_content_container').hide();
                        $('#reply_comment_id').val('0');
                        $('#no_comment').remove();
                        $("#comment_error").text("评论成功")
                    } else {
                        // 显示错误信息
                        $("#comment_error").text(data['message']);
                    }
                },
                error: function (xhr) {
                    console.log(xhr);
                }
            });
            return false;

        });
        function likeChange(obj, content_type, object_id) {
            var is_like = obj.getElementsByClassName("active").length == 0
            $.ajax({
                url: "{% url 'likes:like_change' %}",
                type: "GET",
                data: {
                    content_type: content_type,
                    object_id: object_id,
                    is_like: is_like
                },
                cache: false,
                success: function (data) {
                    if (data['status'] == 'SUCCESS') {
                        // 更新点赞状态
                        var element = $(obj.getElementsByClassName('glyphicon'));
                        if (is_like) {
                            element.addClass("active");
                        } else {
                            element.removeClass("active");
                        }
                        // 更新点赞数量
                        var liked_num = $(obj.getElementsByClassName('liked_num'));
                        liked_num.text(data['liked_num'])
                    } else {
                        if (data["code"] == 400) {
                            $("#login_modal").modal("show")
                        } else {
                            alert(data['message']);
                        }
                    }
                },
                error: function (xhr) {
                    alert(xhr)
                }
            });

        }
        $("#login_modal").submit(function (event) {
            event.preventDefault();
            $.ajax({
                url: "{% url "login_for_modal" %}",
                type: "POST",
                data: {
                    username: $("form input[name=username]").val(),
                    password: $("form input[name=password]").val(),
                },
                cache: false,
                success: function (data) {
                    if (data["status"] == "SUCCESS") {
                        window.location.reload();
                    } else {
                        $("#login_modal_tip").text("用户名或密码不正确")
                    }
                }
            });
        });

    </script>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "base.html" %}
{% load static %}
{% load blog_tags %}
{% block title %}
    我的网站
{% endblock %}
{% block nav_blog_active %}
    active
{% endblock %}
{% block header_extends %}
    <link rel="stylesheet" href="{% static "blog/blog.css" %}">
{% endblock %}
{% block content %}
    <div class="container content">
        <div class="row">
            <div class="col-xs12 col-sm-8 col-md-8 col-lg-8">
                {#                <div class="panel panel-default">#}
                {#                    <div class="panel panel-heading">#}
                {#                        {% block blog_list_title %}#}
                {#                            <博客列表></博客列表>#}
                {#                        {% endblock %}#}
                {#                    </div>#}
                {#                    <div class="panel-body">#}
                {#                        {% for blog in page_of_blogs.object_list %}#}
                {#                            <div class="blog">#}
                {#                                <h3><a href="{% url "blog:blog_detail" blog.id %}">{{ blog.title }}</a></h3>#}
                {#                                <p class="blog-info">#}
                {#                                    <span class="glyphicon glyphicon-tag"></span><a#}
                {#                                        href="{% url "blog:blog_with_type" blog.blog_type.pk %}">{{ blog.blog_type.type_name }}</a>#}
                {#                                    &nbsp;&nbsp;#}
                {#                                    <span class="glyphicon glyphicon-calendar"></span>{{ blog.create_time|date:"Y-m-d" }}#}
                {#                                    &nbsp;&nbsp;#}
                {#                                    <span class="glyphicon glyphicon-eye-open">{{ blog.get_read_num }}</span>#}
                {#                                    &nbsp;&nbsp;#}
                {#                                    <span class="glyphicon glyphicon-comment">({{ blog|comment_sum }})</span>#}
                {#                                </p>#}
                {#                                <p>{{ blog.content|striptags|truncatechars:120 }}</p>#}
                {#                            </div>#}
                {#                        {% empty %}#}
                {#                            <div class="blog">#}
                {#                                <p> --暂无博客-- </p>#}
                {#                            </div>#}
                {#                        {% endfor %}#}
                {#                    </div>#}
                {#                </div>#}
                <div class="mod-info-flow">

                    {% for blog in page_of_blogs.object_list %}

                        <div class="blog">
                            <h3>
                                <div class="panel-title"><a
                                        href="{% url "blog:blog_detail" blog.id %}">{{ blog.title }}</a></div>
                            </h3>
                            <span class="glyphicon glyphicon-tag"></span><a
                                href="{% url "blog:blog_with_type" blog.blog_type.pk %}">{{ blog.blog_type.type_name }}</a>
                            &nbsp;&nbsp;
                            <span class="glyphicon glyphicon-calendar"></span>{{ blog.create_time|date:"Y-m-d" }}
                            &nbsp;&nbsp;
                            <span class="glyphicon glyphicon-eye-open"></span>{{ blog.get_read_num }}
                            &nbsp;&nbsp;
                            <span class="glyphicon glyphicon-comment"></span>{{ blog|comment_sum }}
                            <div class="distance">
                                <p>
                                    {{ blog.content|striptags|truncatechars:180 }}
                                    <a href="{% url "blog:blog_detail" blog.id %}"
                                       class="glyphicon glyphicon-menu-right">阅读更多</a>
                                </p>
                            </div>
                        </div>
                    {% empty %}
                        <div class="blog">
                            <p> --暂无博客-- </p>
                        </div>
                    {% endfor %}

                </div>
                <div class="paginator">
                    <ul class="pagination">
                        <li>
                            {% if page_of_blogs.has_previous %}
                                <a href="?page={{ page_of_blogs.previous_page_number }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            {% else %}
                                <span aria-hidden="true">&laquo;</span>
                            {% endif %}
                        </li>
                        {% block pagination %}
                            {% for page_of_blog in page_range %}
                                {% if page_of_blog == page_of_blogs.number %}
                                    <li class="active"><span>{{ page_of_blog }}</span></li>
                                {% else %}
                                    {% if page_of_blog == "..." %}
                                        <li><span>{{ page_of_blog }}</span></li>
                                    {% else %}
                                        <li>
                                            <a href="{% url "blog:blog_list" %}?page={{ page_of_blog }}">{{ page_of_blog }}</a>
                                        </li>
                                    {% endif %}
                                {% endif %}
                                {#                            <li><a href="?page={{ page_of_blog }}">{{ page_of_blog }}</a></li>#}
                            {% endfor %}
                        {% endblock %}
                        <li>
                            {% if page_of_blogs.has_next %}
                                <a href="?page={{ page_of_blogs.next_page_number }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            {% else %}
                                <span aria-hidden="true">&laquo;</span>
                            {% endif %}
                        </li>
                    </ul>
                    <p>
                        一共有{{ page_of_blogs.paginator.count }}篇博客
                        当前第{{ page_of_blogs.number }}页， 共{{ page_of_blogs.paginator.num_pages }}页
                    </p>
                </div>
            </div>
            <div class="hidden-xs col-sm-4 col-md-4 col-lg-4">
                <div class="panel panel-primary">
                    <div class="panel-heading">博客分类</div>
                    <div class="panel-body">
                        {% for blog_type in blog_types %}
                            <ul class="list-group-item">
                                <a href="{% url "blog:blog_with_type" blog_type.pk %}">{{ blog_type.type_name }}
                                    <span class="badge label-primary">{{ blog_type|count }}</span>
                                </a>
                            </ul>
                        {% empty %}
                            <li>暂无分类</li>
                        {% endfor %}
                    </div>
                </div>
                <div class=" panel panel-primary">
                    <div class="panel-heading">
                        <span>热门文章</span>
                    </div>
                    <ul class="list-group">
                        {% for popular_article in popular_articles %}
                            <li class="list-group-item clearfix">
                                <a href="{% url "blog:blog_detail" popular_article.content_object.id %}">
                                    {{ popular_article.content_object.title }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    {% if page_of_blogs.number == page_of_blogs.paginator.num_pages %}
        {% if page_of_blogs.object_list|length <= 2 %}
            <footer class="nav navbar-inverse navbar-fixed-bottom ">
                <div class="container">
                    <p class="m-0  navbar-brand">Welcome to visit my website,Copyright &copy; Clean Blog 2018</p>
                </div>
                <!-- /.container -->
            </footer>
        {% else %}
            <footer class="nav navbar-inverse  ">
                <div class="container">
                    <p class="m-0  navbar-brand">Welcome to visit my website,Copyright &copy; Clean Blog 2018</p>
                </div>
                <!-- /.container -->
            </footer>
        {% endif %}

    {% else %}
        <footer class="nav navbar-inverse  ">
            <div class="container">
                <p class="m-0  navbar-brand">Welcome to visit my website,Copyright &copy; Clean Blog 2018</p>
            </div>
            <!-- /.container -->
        </footer>
    {% endif %}
{% endblock %}

blog/templates/blog/blogs_with_date.html
{% extends "base.html" %}
{% load static %}
{% load blog_tags %}
{% block title %}
    日期归档
{% endblock %}
{% block nav_blog_active %}
    active
{% endblock %}
{% block header_extends %}
        <link rel="stylesheet" href="{% static "blog/blog_archive.css" %}">
{% endblock %}
{% block content %}
    <div class="archive-container">
        <div class="container archive">
            {% for blog_date in blog_dates %}
                <h2>{{ blog_date.year }}年{{ blog_date.month }}月</h2>
                {% for blog in blog_date|time_count %}
                    <dl class="dl_style">
                        <dt>{{ blog_date|date:"Y-m-d" }}</dt>
                        <dd><a href="{% url "blog:blog_detail" blog.id %}">{{ blog.title  }}</a></dd>
                    </dl>
                {% endfor %}

            {% endfor %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/blogs_with_type.html
{% extends "blog/blog_list.html" %}
{% block title %}
    {{ blog_type.type_name }}
{% endblock %}

{% block blog_list_title %}
    分类：{{ blog_type.type_name }}
{% endblock %}

{% block pagination %}
    {% for page_of_blog in page_range %}
        {% if page_of_blog == page_of_blogs.number %}
            <li class="active"><span>{{ page_of_blog }}</span></li>
        {% else %}
            {% if page_of_blog == "..." %}
                <li><span>{{ page_of_blog }}</span></li>
            {% else %}
                <li>
                    <a href="{% url "blog:blog_with_type" blog_type.pk %}?page={{ page_of_blog }}">{{ page_of_blog }}</a>
                </li>
            {% endif %}
        {% endif %}
        {#                            <li><a href="?page={{ page_of_blog }}">{{ page_of_blog }}</a></li>#}
    {% endfor %}
{% endblock %}