blog/urls.py
from django.urls import path, re_path
from . import views

app_name = "blog"
urlpatterns = [
    # https:localhost:8000/blog/1
    path("", views.blog_list, name="blog_list"),
    path("<int:blog_id>", views.blog_detail, name="blog_detail"),
    path("type/<int:id>", views.blogs_with_type, name="blog_with_type"),
    path("date", views.blogs_with_date, name="blog_with_date"),
    path("about", views.about_me, name="about_me")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from blog import views as blog_views
urlpatterns = [
    path("", blog_views.blog_list, name="home"),
    path('admin/', admin.site.urls),
    path("ckeditor", include("ckeditor_uploader.urls")),
    path("blog/", include("blog.urls")),
    path("comment/", include("comment.urls")),
    path("likes/", include("likes.urls")),
    path("user/", include("user.urls")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "base.css" %}">
    <link rel="stylesheet" href="{% static "bootstrap-3.3.7/css/bootstrap.min.css" %}">
    <script type="text/javascript" src="{% static "jquery.min.js" %}"></script>
    <script type="text/javascript" src="{% static "bootstrap-3.3.7/js/bootstrap.min.js" %}"></script>
    {% block header_extends %}{% endblock %}
</head>
<body>
<div class="jumbotron">
    <div class="container">
        <div class="nav-header">
            <div class="nav pull-left">
                <a href="{% url "blog:blog_list" %}">首页</a>
                <a href="{% url "blog:blog_with_date" %}">归档</a>
                 <a href="{% url "blog:about_me" %}">关于</a>
            </div>
            <div class="nav  navbar-right">
                {% if not user.is_authenticated %}
                    <a class="glyphicon glyphicon-log-in" href="{% url "login" %}?from={{ request.get_full_path }}"></a>
                {% else %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                          >{{ user.username }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url "logout" %}?from={{ request.get_full_path }}">退出登录</a></li>
                        </ul>
                    </li>
                {% endif %}
            </div>
        </div>

        <div class="container header-wrapper ">
            <div class="row">
                <div class="header-content">
                    <div class="header-title">Blog</div>
                </div>
            </div>
        </div>
        <div class="header"></div>
    </div>
</div>
{% block content %}
{% endblock %}
{% block footer %}
    <footer class="nav navbar-inverse  ">
        <div class="container">
            <p class="m-0  navbar-brand foot">Welcome to visit my website,Copyright &copy; Clean Blog 2018</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}
</body>
</html>
{% block script_extedns %}
{% endblock %}

templates/error.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    我的网站|错误
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    {{ message }}，<a href="{{ redirect_to }}">返回</a>
{% endblock %}